# Generated by Django 4.2.5 on 2023-10-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='name',
        ),
    ]
