# Generated by Django 4.2.5 on 2023-10-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_soldproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='Products.product'),
        ),
    ]
