# Generated by Django 4.2.5 on 2023-10-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_soldproduct_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
