# Generated by Django 4.2.5 on 2023-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_soldproduct_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='product_count',
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
